# set directories
key_file : "/dir/to/Key.xlsx"
data_dir : "/dir/to/data/"
out_dir : "/dir/to/output/"
experiment_IDs_exclude: []
pixel_no_per_retina : 10000
image_types : ['GFP']
# decide which experiment shall be loaded for plotting results
load_conditions :  ['CDH5CreERT2;iSureCre;YesFloxFlox', 'CDH5CreERT2 iSureCre']
# decide if kde and individual histograms shall be plotted
plot_kde : False
plot_individual_hist : False
plot_kde : False
plot_cond_kde : True
plot_individual_hist : False
radial_bins : [[0,1200]]
time_points : ['P3_P7', 'P3_P15'] # time points for plotting histograms and kde plots
number_ks_test : 1
